import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { useApp } from '@/context/AppContext';
import { NotificationPreferences } from '@/data/seed';
import { colors } from '@/theme/colors';

const rows:[keyof NotificationPreferences,string,string,keyof typeof Ionicons.glyphMap][]=[
 ['messages','Messages','New direct messages','chatbubble-outline'],['social','Social','Follows, friends, comments and tags','people-outline'],['events','Events','Invites and request approvals','calendar-outline'],['reminders','Reminders','Useful reminders before events','alarm-outline'],
];
export default function NotificationSettings(){
 const router=useRouter(); const {notificationPreferences,updateNotificationPreferences,enablePushNotifications}=useApp(); const [prefs,setPrefs]=useState(notificationPreferences); const [busy,setBusy]=useState(false);
 const toggle=async(key:keyof NotificationPreferences,value:boolean)=>{const next={...prefs,[key]:value};setPrefs(next);try{await updateNotificationPreferences(next);}catch{setPrefs(prefs);Alert.alert('Couldn’t save setting','Try again.');}};
 const enable=async()=>{setBusy(true);try{const r=await enablePushNotifications();if(r.enabled)Alert.alert('Push notifications are on','FOMO can now send the notification categories you’ve enabled.');else if(r.reason==='permission')Alert.alert('Notifications are off','You can enable FOMO notifications later in iPhone Settings.');else if(r.reason==='project_id')Alert.alert('Development build needed','This build does not have an EAS project ID yet. In-app notifications still work normally.');else Alert.alert('Push isn’t available yet','In-app notifications still work normally.');}finally{setBusy(false);}};
 return <SafeAreaView style={styles.safe}><View style={styles.head}><Pressable onPress={()=>router.back()} style={styles.back}><Ionicons name="arrow-back" color={colors.text} size={21}/></Pressable><Text style={styles.title}>Notifications</Text><View style={{width:38}}/></View><View style={styles.content}><Text style={styles.kicker}>PUSH SETTINGS</Text><Text style={styles.lead}>Only get the stuff that actually matters.</Text>
  <Pressable onPress={enable} disabled={busy} style={styles.enable}><View style={styles.enableIcon}><Ionicons name="notifications-outline" color={colors.text} size={21}/></View><View style={{flex:1}}><Text style={styles.enableTitle}>{busy?'Checking…':'Enable device push'}</Text><Text style={styles.enableSub}>Optional. FOMO still works if you say no.</Text></View><Ionicons name="chevron-forward" color={colors.subtle} size={17}/></Pressable>
  <View style={styles.group}>{rows.map(([key,title,sub,icon])=><View key={key} style={styles.row}><View style={styles.icon}><Ionicons name={icon} color={colors.text} size={18}/></View><View style={{flex:1}}><Text style={styles.rowTitle}>{title}</Text><Text style={styles.rowSub}>{sub}</Text></View><Switch value={prefs[key]} onValueChange={v=>toggle(key,v)} trackColor={{false:colors.surface3,true:colors.accent}} thumbColor={colors.white}/></View>)}</View>
 </View></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},head:{height:58,paddingHorizontal:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:38,height:38,borderRadius:19,alignItems:'center',justifyContent:'center'},title:{color:colors.text,fontSize:15,fontWeight:'900'},content:{padding:16},kicker:{color:colors.accent2,fontSize:9,fontWeight:'900',letterSpacing:1},lead:{color:colors.text,fontSize:25,lineHeight:29,fontWeight:'900',marginTop:5,marginBottom:18},enable:{minHeight:72,borderRadius:22,backgroundColor:colors.surface,padding:12,flexDirection:'row',alignItems:'center',borderWidth:StyleSheet.hairlineWidth,borderColor:colors.line},enableIcon:{width:44,height:44,borderRadius:22,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center',marginRight:10},enableTitle:{color:colors.text,fontSize:12,fontWeight:'900'},enableSub:{color:colors.muted,fontSize:9.5,marginTop:3},group:{marginTop:14,borderRadius:23,backgroundColor:colors.surface,overflow:'hidden',borderWidth:StyleSheet.hairlineWidth,borderColor:colors.line},row:{minHeight:69,paddingHorizontal:12,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line},icon:{width:37,height:37,borderRadius:19,backgroundColor:colors.surface2,alignItems:'center',justifyContent:'center',marginRight:10},rowTitle:{color:colors.text,fontSize:11.5,fontWeight:'800'},rowSub:{color:colors.muted,fontSize:9.3,marginTop:2}});
